language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.4.10
    - DJANGO_VERSION=1.5.5
    - DJANGO_VERSION=1.6.2
install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements/global.txt --use-mirrors
    - pip install -r requirements/travis.txt --use-mirrors
script:
    - "cd demo"
    - "python manage.py test demo"
